import mongoose from "mongoose";
import dotenv from "dotenv";
import Listing from "../api/models/listing.model.js";

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const ownerId = "691c5ae284eaed4734b34f0f";

const listings = [
    {
        title: "3BHK Apartment in OMR",
        description: "Spacious 3BHK near IT corridor.",
        price: 7200000,
        type: "sale",
        bedrooms: 3,
        bathrooms: 2,
        areaSqFt: 1350,
        address: { street: "OMR Road", city: "Chennai", state: "TN", postalCode: "600096" },
        image: { url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994", public_id: "seed1" },
        owner: ownerId,
    },
    {
        title: "2BHK Flat in Velachery",
        description: "Well connected 2BHK near metro.",
        price: 4800000,
        type: "sale",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1050,
        address: { street: "Velachery Main Rd", city: "Chennai", state: "TN", postalCode: "600042" },
        image: { url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be", public_id: "seed2" },
        owner: ownerId,
    },
    {
        title: "1BHK for Rent in T Nagar",
        description: "Affordable 1BHK for bachelors.",
        price: 18000,
        type: "rent",
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 550,
        address: { street: "Usman Road", city: "Chennai", state: "TN", postalCode: "600017" },
        image: { url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c", public_id: "seed3" },
        owner: ownerId,
    },
    {
        title: "Villa in ECR",
        description: "Luxury beachside villa.",
        price: 24000000,
        type: "sale",
        bedrooms: 4,
        bathrooms: 4,
        areaSqFt: 3200,
        address: { street: "ECR", city: "Chennai", state: "TN", postalCode: "600115" },
        image: { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c", public_id: "seed4" },
        owner: ownerId,
    },
    {
        title: "2BHK Apartment in Whitefield",
        description: "IT professionals preferred.",
        price: 42000,
        type: "rent",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1100,
        address: { street: "Whitefield", city: "Bangalore", state: "KA", postalCode: "560066" },
        image: { url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6", public_id: "seed5" },
        owner: ownerId,
    },
    {
        title: "3BHK Flat in Electronic City",
        description: "Near tech parks.",
        price: 6500000,
        type: "sale",
        bedrooms: 3,
        bathrooms: 3,
        areaSqFt: 1400,
        address: { street: "Electronic City", city: "Bangalore", state: "KA", postalCode: "560100" },
        image: { url: "https://images.unsplash.com/photo-1576941089067-2de3c901e126", public_id: "seed6" },
        owner: ownerId,
    },
    {
        title: "Studio Apartment in Pune",
        description: "Ideal for working professionals.",
        price: 22000,
        type: "rent",
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 450,
        address: { street: "Hinjewadi", city: "Pune", state: "MH", postalCode: "411057" },
        image: { url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914", public_id: "seed7" },
        owner: ownerId,
    },
    {
        title: "3BHK Apartment in Gachibowli",
        description: "Premium gated community.",
        price: 8200000,
        type: "sale",
        bedrooms: 3,
        bathrooms: 3,
        areaSqFt: 1500,
        address: { street: "Gachibowli", city: "Hyderabad", state: "TS", postalCode: "500032" },
        image: { url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde", public_id: "seed8" },
        owner: ownerId,
    },
    {
        title: "2BHK Flat in Kochi",
        description: "Sea breeze and calm locality.",
        price: 5200000,
        type: "sale",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1150,
        address: { street: "Marine Drive", city: "Kochi", state: "KL", postalCode: "682031" },
        image: { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83", public_id: "seed9" },
        owner: ownerId,
    },
    {
        title: "Independent House in Coimbatore",
        description: "Peaceful residential area.",
        price: 9800000,
        type: "sale",
        bedrooms: 4,
        bathrooms: 3,
        areaSqFt: 2600,
        address: { street: "RS Puram", city: "Coimbatore", state: "TN", postalCode: "641002" },
        image: { url: "https://images.unsplash.com/photo-1592595896551-12b371d546d5", public_id: "seed10" },
        owner: ownerId,
    },

    // ---- RENTAL HEAVY (for recommendation testing) ----
    {
        title: "1BHK Rent in Anna Nagar",
        description: "Close to schools and metro.",
        price: 16000,
        type: "rent",
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 600,
        address: { street: "Anna Nagar", city: "Chennai", state: "TN", postalCode: "600040" },
        image: { url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6", public_id: "seed11" },
        owner: ownerId,
    },
    {
        title: "2BHK Rent in Madipakkam",
        description: "Family friendly locality.",
        price: 22000,
        type: "rent",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 950,
        address: { street: "Madipakkam", city: "Chennai", state: "TN", postalCode: "600091" },
        image: { url: "https://plus.unsplash.com/premium_photo-1661915661139-5b6a4e4a6fcc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW9kZXJuJTIwaG91c2V8ZW58MHx8MHx8fDA%3D", public_id: "seed12" },
        owner: ownerId,
    },
    {
        title: "3BHK Rent in HSR Layout",
        description: "Spacious flat for families.",
        price: 48000,
        type: "rent",
        bedrooms: 3,
        bathrooms: 3,
        areaSqFt: 1450,
        address: { street: "HSR Layout", city: "Bangalore", state: "KA", postalCode: "560102" },
        image: { url: "https://images.unsplash.com/photo-1599423300746-b62533397364", public_id: "seed13" },
        owner: ownerId,
    },
    {
        title: "Villa Rent in Jubilee Hills",
        description: "Luxury villa with garden.",
        price: 120000,
        type: "rent",
        bedrooms: 4,
        bathrooms: 4,
        areaSqFt: 3500,
        address: { street: "Jubilee Hills", city: "Hyderabad", state: "TS", postalCode: "500033" },
        image: { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c", public_id: "seed14" },
        owner: ownerId,
    },
    {
        title: "2BHK Rent in Viman Nagar",
        description: "Near airport and IT parks.",
        price: 30000,
        type: "rent",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1000,
        address: { street: "Viman Nagar", city: "Pune", state: "MH", postalCode: "411014" },
        image: { url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b", public_id: "seed15" },
        owner: ownerId,
    },

    // ---- MIXED CITIES ----
    {
        title: "2BHK Flat in Trivandrum",
        description: "Close to city center.",
        price: 4100000,
        type: "sale",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1000,
        address: { street: "Pattom", city: "Trivandrum", state: "KL", postalCode: "695004" },
        image: { url: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c", public_id: "seed16" },
        owner: ownerId,
    },
    {
        title: "3BHK Apartment in Noida",
        description: "Gated society with amenities.",
        price: 7600000,
        type: "sale",
        bedrooms: 3,
        bathrooms: 2,
        areaSqFt: 1550,
        address: { street: "Sector 62", city: "Noida", state: "UP", postalCode: "201309" },
        image: { url: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb", public_id: "seed17" },
        owner: ownerId,
    },
    {
        title: "1BHK Rent in Salt Lake",
        description: "Near office hubs.",
        price: 15000,
        type: "rent",
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 500,
        address: { street: "Salt Lake", city: "Kolkata", state: "WB", postalCode: "700091" },
        image: { url: "https://images.unsplash.com/photo-1560448075-bb485b067938", public_id: "seed18" },
        owner: ownerId,
    },
    {
        title: "4BHK Independent House in Indore",
        description: "Spacious home with parking.",
        price: 8900000,
        type: "sale",
        bedrooms: 4,
        bathrooms: 3,
        areaSqFt: 2800,
        address: { street: "Vijay Nagar", city: "Indore", state: "MP", postalCode: "452010" },
        image: { url: "https://images.unsplash.com/photo-1600585154780-7c6f1fa8f4b3", public_id: "seed19" },
        owner: ownerId,
    },
    {
        title: "2BHK Flat in Ahmedabad",
        description: "Well ventilated modern flat.",
        price: 3800000,
        type: "sale",
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 950,
        address: { street: "Satellite", city: "Ahmedabad", state: "GJ", postalCode: "380015" },
        image: { url: "https://images.unsplash.com/photo-1592595896616-c37162298647", public_id: "seed20" },
        owner: ownerId,
    },
];

const seedDB = async () => {
    try {
        await Listing.deleteMany();
        await Listing.insertMany(listings);
        console.log("✅ 20 listings seeded successfully");
        process.exit();
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
};

seedDB();
